# Generated by Django 4.2.17 on 2025-03-06 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['payment_date'], 'verbose_name': 'платеж', 'verbose_name_plural': 'платежы'},
        ),
    ]
